import { SceneType, Word } from './types';

export const WORDS: Word[] = [
  // Animals
  { id: 'a1', english: 'Dog', chinese: '小狗', image: '🐶', scene: SceneType.ANIMALS },
  { id: 'a2', english: 'Cat', chinese: '小猫', image: '🐱', scene: SceneType.ANIMALS },
  { id: 'a3', english: 'Rabbit', chinese: '兔子', image: '🐰', scene: SceneType.ANIMALS },
  { id: 'a4', english: 'Lion', chinese: '狮子', image: '🦁', scene: SceneType.ANIMALS },
  { id: 'a5', english: 'Elephant', chinese: '大象', image: '🐘', scene: SceneType.ANIMALS },
  { id: 'a6', english: 'Monkey', chinese: '猴子', image: '🐒', scene: SceneType.ANIMALS },
  { id: 'a7', english: 'Tiger', chinese: '老虎', image: '🐯', scene: SceneType.ANIMALS },
  { id: 'a8', english: 'Giraffe', chinese: '长颈鹿', image: '🦒', scene: SceneType.ANIMALS },
  { id: 'a9', english: 'Zebra', chinese: '斑马', image: '🦓', scene: SceneType.ANIMALS },
  { id: 'a10', english: 'Panda', chinese: '熊猫', image: '🐼', scene: SceneType.ANIMALS },
  { id: 'a11', english: 'Bear', chinese: '熊', image: '🐻', scene: SceneType.ANIMALS },
  { id: 'a12', english: 'Fox', chinese: '狐狸', image: '🦊', scene: SceneType.ANIMALS },
  { id: 'a13', english: 'Pig', chinese: '猪', image: '🐷', scene: SceneType.ANIMALS },
  { id: 'a14', english: 'Cow', chinese: '奶牛', image: '🐮', scene: SceneType.ANIMALS },
  { id: 'a15', english: 'Sheep', chinese: '绵羊', image: '🐑', scene: SceneType.ANIMALS },
  { id: 'a16', english: 'Chicken', chinese: '鸡', image: '🐔', scene: SceneType.ANIMALS },
  { id: 'a17', english: 'Duck', chinese: '鸭子', image: '🦆', scene: SceneType.ANIMALS },
  { id: 'a18', english: 'Frog', chinese: '青蛙', image: '🐸', scene: SceneType.ANIMALS },
  { id: 'a19', english: 'Snake', chinese: '蛇', image: '🐍', scene: SceneType.ANIMALS },
  { id: 'a20', english: 'Turtle', chinese: '乌龟', image: '🐢', scene: SceneType.ANIMALS },
  
  // Food
  { id: 'f1', english: 'Apple', chinese: '苹果', image: '🍎', scene: SceneType.FOOD },
  { id: 'f2', english: 'Banana', chinese: '香蕉', image: '🍌', scene: SceneType.FOOD },
  { id: 'f3', english: 'Milk', chinese: '牛奶', image: '🥛', scene: SceneType.FOOD },
  { id: 'f4', english: 'Bread', chinese: '面包', image: '🍞', scene: SceneType.FOOD },
  { id: 'f5', english: 'Cake', chinese: '蛋糕', image: '🍰', scene: SceneType.FOOD },
  { id: 'f6', english: 'Orange', chinese: '橙子', image: '🍊', scene: SceneType.FOOD },
  { id: 'f7', english: 'Grape', chinese: '葡萄', image: '🍇', scene: SceneType.FOOD },
  { id: 'f8', english: 'Strawberry', chinese: '草莓', image: '🍓', scene: SceneType.FOOD },
  { id: 'f9', english: 'Watermelon', chinese: '西瓜', image: '🍉', scene: SceneType.FOOD },
  { id: 'f10', english: 'Cherry', chinese: '樱桃', image: '🍒', scene: SceneType.FOOD },
  { id: 'f11', english: 'Egg', chinese: '鸡蛋', image: '🥚', scene: SceneType.FOOD },
  { id: 'f12', english: 'Cheese', chinese: '奶酪', image: '🧀', scene: SceneType.FOOD },
  { id: 'f13', english: 'Pizza', chinese: '披萨', image: '🍕', scene: SceneType.FOOD },
  { id: 'f14', english: 'Burger', chinese: '汉堡', image: '🍔', scene: SceneType.FOOD },
  { id: 'f15', english: 'Fries', chinese: '薯条', image: '🍟', scene: SceneType.FOOD },
  { id: 'f16', english: 'Ice Cream', chinese: '冰淇淋', image: '🍦', scene: SceneType.FOOD },
  { id: 'f17', english: 'Cookie', chinese: '曲奇', image: '🍪', scene: SceneType.FOOD },
  { id: 'f18', english: 'Candy', chinese: '糖果', image: '🍬', scene: SceneType.FOOD },
  { id: 'f19', english: 'Juice', chinese: '果汁', image: '🧃', scene: SceneType.FOOD },
  { id: 'f20', english: 'Water', chinese: '水', image: '💧', scene: SceneType.FOOD },

  // Colors
  { id: 'c1', english: 'Red', chinese: '红色', image: '🔴', scene: SceneType.COLORS },
  { id: 'c2', english: 'Blue', chinese: '蓝色', image: '🔵', scene: SceneType.COLORS },
  { id: 'c3', english: 'Green', chinese: '绿色', image: '🟢', scene: SceneType.COLORS },
  { id: 'c4', english: 'Yellow', chinese: '黄色', image: '🟡', scene: SceneType.COLORS },
  { id: 'c5', english: 'Purple', chinese: '紫色', image: '🟣', scene: SceneType.COLORS },
  { id: 'c6', english: 'Orange', chinese: '橙色', image: '🟠', scene: SceneType.COLORS },
  { id: 'c7', english: 'Pink', chinese: '粉色', image: '🌸', scene: SceneType.COLORS },
  { id: 'c8', english: 'Brown', chinese: '棕色', image: '🟤', scene: SceneType.COLORS },
  { id: 'c9', english: 'Black', chinese: '黑色', image: '⚫', scene: SceneType.COLORS },
  { id: 'c10', english: 'White', chinese: '白色', image: '⚪', scene: SceneType.COLORS },
  { id: 'c11', english: 'Gray', chinese: '灰色', image: '🔘', scene: SceneType.COLORS },
  { id: 'c12', english: 'Gold', chinese: '金色', image: '✨', scene: SceneType.COLORS },
  { id: 'c13', english: 'Silver', chinese: '银色', image: '🥈', scene: SceneType.COLORS },
  { id: 'c14', english: 'Rainbow', chinese: '彩虹', image: '🌈', scene: SceneType.COLORS },
  { id: 'c15', english: 'Dark Blue', chinese: '深蓝色', image: '🌌', scene: SceneType.COLORS },
  { id: 'c16', english: 'Light Blue', chinese: '浅蓝色', image: '💎', scene: SceneType.COLORS },
  { id: 'c17', english: 'Bright Red', chinese: '鲜红色', image: '🔥', scene: SceneType.COLORS },
  { id: 'c18', english: 'Dark Green', chinese: '深绿色', image: '🌲', scene: SceneType.COLORS },
  { id: 'c19', english: 'Light Green', chinese: '浅绿色', image: '🌱', scene: SceneType.COLORS },
  { id: 'c20', english: 'Sky Blue', chinese: '天蓝色', image: '☁️', scene: SceneType.COLORS },

  // Shapes
  { id: 's1', english: 'Circle', chinese: '圆形', image: '⭕', scene: SceneType.SHAPES },
  { id: 's2', english: 'Square', chinese: '正方形', image: '⬛', scene: SceneType.SHAPES },
  { id: 's3', english: 'Triangle', chinese: '三角形', image: '🔺', scene: SceneType.SHAPES },
  { id: 's4', english: 'Star', chinese: '星形', image: '⭐', scene: SceneType.SHAPES },
  { id: 's5', english: 'Heart', chinese: '心形', image: '❤️', scene: SceneType.SHAPES },
  { id: 's6', english: 'Oval', chinese: '椭圆形', image: '🥚', scene: SceneType.SHAPES },
  { id: 's7', english: 'Rectangle', chinese: '长方形', image: '🧱', scene: SceneType.SHAPES },
  { id: 's8', english: 'Diamond', chinese: '菱形', image: '💠', scene: SceneType.SHAPES },
  { id: 's9', english: 'Pentagon', chinese: '五边形', image: '⬠', scene: SceneType.SHAPES },
  { id: 's10', english: 'Hexagon', chinese: '六边形', image: '⬡', scene: SceneType.SHAPES },
  { id: 's11', english: 'Crescent', chinese: '新月形', image: '🌙', scene: SceneType.SHAPES },
  { id: 's12', english: 'Cross', chinese: '十字形', image: '➕', scene: SceneType.SHAPES },
  { id: 's13', english: 'Arrow', chinese: '箭头', image: '➡️', scene: SceneType.SHAPES },
  { id: 's14', english: 'Cloud', chinese: '云朵形', image: '☁️', scene: SceneType.SHAPES },
  { id: 's15', english: 'Sun', chinese: '太阳形', image: '☀️', scene: SceneType.SHAPES },
  { id: 's16', english: 'Moon', chinese: '月亮形', image: '🌑', scene: SceneType.SHAPES },
  { id: 's17', english: 'Drop', chinese: '水滴形', image: '💧', scene: SceneType.SHAPES },
  { id: 's18', english: 'Ring', chinese: '圆环', image: '💍', scene: SceneType.SHAPES },
  { id: 's19', english: 'Cube', chinese: '立方体', image: '🧊', scene: SceneType.SHAPES },
  { id: 's20', english: 'Sphere', chinese: '球体', image: '⚽', scene: SceneType.SHAPES },

  // Body Parts
  { id: 'b1', english: 'Eye', chinese: '眼睛', image: '👁️', scene: SceneType.BODY_PARTS },
  { id: 'b2', english: 'Nose', chinese: '鼻子', image: '👃', scene: SceneType.BODY_PARTS },
  { id: 'b3', english: 'Mouth', chinese: '嘴巴', image: '👄', scene: SceneType.BODY_PARTS },
  { id: 'b4', english: 'Ear', chinese: '耳朵', image: '👂', scene: SceneType.BODY_PARTS },
  { id: 'b5', english: 'Hand', chinese: '手', image: '✋', scene: SceneType.BODY_PARTS },
  { id: 'b6', english: 'Foot', chinese: '脚', image: '🦶', scene: SceneType.BODY_PARTS },
  { id: 'b7', english: 'Arm', chinese: '手臂', image: '💪', scene: SceneType.BODY_PARTS },
  { id: 'b8', english: 'Leg', chinese: '腿', image: '🦵', scene: SceneType.BODY_PARTS },
  { id: 'b9', english: 'Head', chinese: '头', image: '👤', scene: SceneType.BODY_PARTS },
  { id: 'b10', english: 'Hair', chinese: '头发', image: '💇', scene: SceneType.BODY_PARTS },
  { id: 'b11', english: 'Face', chinese: '脸', image: '😊', scene: SceneType.BODY_PARTS },
  { id: 'b12', english: 'Shoulder', chinese: '肩膀', image: '👕', scene: SceneType.BODY_PARTS },
  { id: 'b13', english: 'Knee', chinese: '膝盖', image: '🦵', scene: SceneType.BODY_PARTS },
  { id: 'b14', english: 'Finger', chinese: '手指', image: '☝️', scene: SceneType.BODY_PARTS },
  { id: 'b15', english: 'Toe', chinese: '脚趾', image: '🦶', scene: SceneType.BODY_PARTS },
  { id: 'b16', english: 'Tongue', chinese: '舌头', image: '👅', scene: SceneType.BODY_PARTS },
  { id: 'b17', english: 'Teeth', chinese: '牙齿', image: '🦷', scene: SceneType.BODY_PARTS },
  { id: 'b18', english: 'Neck', chinese: '脖子', image: '🧣', scene: SceneType.BODY_PARTS },
  { id: 'b19', english: 'Back', chinese: '背部', image: '🎒', scene: SceneType.BODY_PARTS },
  { id: 'b20', english: 'Stomach', chinese: '肚子', image: '🤰', scene: SceneType.BODY_PARTS },

  // Daily Items
  { id: 'd1', english: 'Shirt', chinese: '衬衫', image: '👕', scene: SceneType.DAILY_ITEMS },
  { id: 'd2', english: 'Shoes', chinese: '鞋子', image: '👟', scene: SceneType.DAILY_ITEMS },
  { id: 'd3', english: 'Book', chinese: '书', image: '📖', scene: SceneType.DAILY_ITEMS },
  { id: 'd4', english: 'Chair', chinese: '椅子', image: '🪑', scene: SceneType.DAILY_ITEMS },
  { id: 'd5', english: 'Bed', chinese: '床', image: '🛏️', scene: SceneType.DAILY_ITEMS },
  { id: 'd6', english: 'Table', chinese: '桌子', image: '🪑', scene: SceneType.DAILY_ITEMS },
  { id: 'd7', english: 'Lamp', chinese: '灯', image: '💡', scene: SceneType.DAILY_ITEMS },
  { id: 'd8', english: 'Clock', chinese: '时钟', image: '⏰', scene: SceneType.DAILY_ITEMS },
  { id: 'd9', english: 'Phone', chinese: '电话', image: '📱', scene: SceneType.DAILY_ITEMS },
  { id: 'd10', english: 'Computer', chinese: '电脑', image: '💻', scene: SceneType.DAILY_ITEMS },
  { id: 'd11', english: 'Bag', chinese: '包包', image: '🎒', scene: SceneType.DAILY_ITEMS },
  { id: 'd12', english: 'Cup', chinese: '杯子', image: '🥛', scene: SceneType.DAILY_ITEMS },
  { id: 'd13', english: 'Spoon', chinese: '勺子', image: '🥄', scene: SceneType.DAILY_ITEMS },
  { id: 'd14', english: 'Fork', chinese: '叉子', image: '🍴', scene: SceneType.DAILY_ITEMS },
  { id: 'd15', english: 'Plate', chinese: '盘子', image: '🍽️', scene: SceneType.DAILY_ITEMS },
  { id: 'd16', english: 'Soap', chinese: '肥皂', image: '🧼', scene: SceneType.DAILY_ITEMS },
  { id: 'd17', english: 'Towel', chinese: '毛巾', image: '🧣', scene: SceneType.DAILY_ITEMS },
  { id: 'd18', english: 'Brush', chinese: '刷子', image: '🪥', scene: SceneType.DAILY_ITEMS },
  { id: 'd19', english: 'Key', chinese: '钥匙', image: '🔑', scene: SceneType.DAILY_ITEMS },
  { id: 'd20', english: 'Umbrella', chinese: '雨伞', image: '☂️', scene: SceneType.DAILY_ITEMS },
];

export const SCENES = [
  { type: SceneType.ANIMALS, icon: '🐶', color: 'bg-orange-400' },
  { type: SceneType.FOOD, icon: '🍎', color: 'bg-red-400' },
  { type: SceneType.COLORS, icon: '🎨', color: 'bg-blue-400' },
  { type: SceneType.SHAPES, icon: '🔷', color: 'bg-purple-400' },
  { type: SceneType.BODY_PARTS, icon: '👃', color: 'bg-pink-400' },
  { type: SceneType.DAILY_ITEMS, icon: '👕', color: 'bg-teal-400' },
];
